<?php

/**
 * @file
 * Primary module hooks for bonnie module.
 */

use Drupal\Core\Render\Element;

/**
 * Implements hook_theme().
 */
function bonnie_theme($existing, $type, $theme, $path) {
  return [
    // Default template for a bonnie module.
    'bonnie_template' => [
      'variables' => [
        'form' => NULL,
        'view' => NULL,
      ],
    ],
    'bonnie' => [
      'render element' => 'elements',
      'template' => 'bonnie',
    ],
  ];
}

/**
 * Implements hook_entity_type_alter().
 */
function bonnie_entity_type_alter(array &$entity_types) {
  // Adding class for bonnie form.
  $bonnie = &$entity_types['bonnie'];
  $bonnie->setFormClass('bonnie_form', 'Drupal\bonnie\Form\BonnieForm');
}

/**
 * Prepares variables for Bonnie templates.
 *
 * Default template: bonnie.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An associative array containing the user information and any
 *   - attributes: HTML attributes for the containing element.
 */
function template_preprocess_bonnie(array &$variables) {
  // Fetch Bonnie Entity Object.
  $bonnie = $variables['elements']['#bonnie'];

  // Helpful $content variable for templates.
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
}

